

const students = [{
  "id": 1,
  first_name: "Homerus",
  last_name: "Eccleston",
  email: "heccleston0@latimes.com",
  gender: "Male",
  Dateofbirth: 2012
}, {
  id: 2,
  first_name: "Maddalena",
  last_name: "Ritchings",
  email: "mritchings1@mac.com",
  gender: "Female",
  Dateofbirth: 2009
}, {
  id: 3,
  first_name: "Esther",
  last_name: "Calliss",
  email: "ecalliss2@un.org",
  gender: "Female",
  Dateofbirth: 2016
}, {
  id: 4,
  first_name: "Jarad",
  last_name: "Hursey",
  email: "jhursey3@wordpress.org",
  gender: "Male",
  Dateofbirth: 2024
}, {
  id: 5,
  first_name: "Dianne",
  last_name: "Snare",
  email: "dsnare4@nasa.gov",
  gender: "Female",
  Dateofbirth: 2005
}, {
  id: 6,
  first_name: "Julietta",
  last_name: "Tames",
  email: "jtames5@oakley.com",
  gender: "Female",
  Dateofbirth: 2010
}, {
  id: 7,
  first_name: "Sabra",
  last_name: "Manhare",
  email: "smanhare6@ox.ac.uk",
  gender: "Female",
  Dateofbirth: 2004
}, {
  id: 8,
  first_name: "Laverna",
  last_name: "Wildblood",
  email: "lwildblood7@pen.io",
  gender: "Female",
  Dateofbirth: 1996
}, {
  id: 9,
  first_name: "Odelia",
  last_name: "Billham",
  email: "obillham8@ifeng.com",
  gender: "Female",
  Dateofbirth: 2003
}, {
  id: 10,
  first_name: "Celestia",
  last_name: "Dougharty",
  email: "cdougharty9@gov.uk",
  gender: "Female",
  Dateofbirth: 2003
}, {
  id: 11,
  first_name: "Haydon",
  last_name: "De Mico",
  email: "hdemicoa@usnews.com",
  gender: "Male",
  Dateofbirth: 2013
}, {
  id: 12,
  first_name: "Benson",
  last_name: "McIleen",
  email: "bmcileenb@instagram.com",
  gender: "Male",
  Dateofbirth: 1995
}, {
  id: 13,
  first_name: "Addie",
  last_name: "Austing",
  email: "aaustingc@freewebs.com",
  gender: "Female",
  Dateofbirth: 2015
}, {
  id: 14,
  first_name: "Alanah",
  last_name: "Milliken",
  email: "amillikend@noaa.gov",
  gender: "Female",
  Dateofbirth: 2012
}, {
  id: 15,
  first_name: "Tedda",
  last_name: "Broadwood",
  email: "tbroadwoode@reddit.com",
  gender: "Female",
  Dateofbirth: 2001
}, {
  id: 16,
  first_name: "Edithe",
  last_name: "Atkirk",
  email: "eatkirkf@goo.gl",
  gender: "Female",
  Dateofbirth: 1993
}, {
  id: 17,
  first_name: "Carrol",
  last_name: "Baudinet",
  email: "cbaudinetg@un.org",
  gender: "Male",
  Dateofbirth: 2012
}, {
  id: 18,
  first_name: "Murial",
  last_name: "Breawood",
  email: "mbreawoodh@booking.com",
  gender: "Female",
  Dateofbirth: 2012
}, {
  id: 19,
  first_name: "Elsa",
  last_name: "Dearn",
  email: "edearni@slate.com",
  gender: "Female",
  Dateofbirth: 1968
}, {
  id: 20,
  first_name: "Bogart",
  last_name: "Corey",
  email: "bcoreyj@stanford.edu",
  gender: "Male",
  Dateofbirth: 2000
}]

export { students}